### ISSUE TITLE
Unable to set ``includeAll`` or ``allFormat`` option for Dashboard Variable

### ISSUE THREAD

**Issue by urianawu** [grafana/grafana-foundation-sdk#17]
I'm using the Typescript SDK to build our dashboard and it's been super helpful! However I do notice that the [VariableModel](https://github.com/grafana/grafana-foundation-sdk/blob/next%2Bcog-v0.0.x/typescript/src/dashboard/types_gen.ts#L161) does not seem to have ``includeAll`` or ``allFormat`` properties which is [listed as part of JSON model](https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/view-dashboard-json-model/#templating) for Grafana 10.2.

Is this intentional? If yes, can you show how to denote a variable to include an option that is ``All``?

Thanks!

---
As a temp fix I have extended the VariableModel in my pkg and added these properties.

**Comment by K-Phoen** [comment]
Hey!

Thanks for reporting this!

This is definitely not intentional, it appears that these fields aren't part of the [schemas used to generate this library](https://github.com/grafana/kind-registry/blob/6fb5506d4a05327e4c70eeaefd0ce47ca9257d3b/grafana/next/core/dashboard/dashboard.cue#L175).
I'll look into getting the schema updated and will let you know when a fix lands in this repo :) (might take a bit of time due to the end-of-year vacation)

**Comment by K-Phoen** [comment]
Small update here: the schema for dashboard variables is being fixed in [this PR](https://github.com/grafana/grafana/pull/79236). While we wait for it to be merged and backported to previous versions of Grafana, I [manually apply similar changes via cog](https://github.com/grafana/cog/pull/216).

Meaning that this issue should now be resolved :)
